### ISSUE TITLE
some questions

### ISSUE THREAD

**Issue by Septemberqxy** [irsisyphus/deepsketch2face#1]
Hi authors of deepsketh2face,when reading your paper i meet some problems.
In the chapter 4.3-Network Architecture you mentioned 66 coefficients in _shape-level input_.
I'm confused about how to get these 66 coefficients from my input sketch.
I'd appreciate if you can help me .My email is 17712369523@163.com,thanks!

**Comment by irsisyphus** [comment]
See the sentence above:

> To make full use of the information from the sketch, we directly sample a fixed number of points on the silhouette and feature lines and represent the 2D position of these sample points via another bilinear model, where the dimensions for the identity and expression modes are still set to 50 and 16.

If you want to reproduce this, you may consider sampling them yourself. There are no pre-set networks for this process.

Also, GitHub Issues should be a place to submit bugs. If you have any questions, please contact me via email. Thanks.
